SELECT E.DEPARTMENT_ID ,
       D.DEPARTMENT_NAME,
       AVG(E.SALARY)
       
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D

ON(D.DEPARTMENT_ID = E.DEPARTMENT_ID)

HAVING AVG(SALARY) > 500 
GROUP BY E.DEPARTMENT_ID,D.DEPARTMENT_NAME;

